export default{
    host:'https://test.youbaobao.xyz:18081',
    appId:'wxafba059ca1c401d2',//微信小程序APPId
    AppSecret:'c7e75d8378b4828d323ab300a0bc3a3a',//小程序密钥
    homeData:'/book/home/v2',//获取首页数据
    recommend:'/book/home/recommend/v2',//获取为你推荐数据
    freeRead:'/book/home/freeRead/v2',//获取免费阅读数据
    hotBook:'/book/home/hotBook/v2',//获取当前最热数据
    wxOpenId:'/openId/get',//获取微信小程序openId
    wxRegister:'/user/register',//获取微信小程序用户注册
    hotSearchWord:'/book/hot-search',//获取热门搜索词
    search:'/book/search',//关键词搜索
    detail:'/book/detail',//获取图书详情
    bookCatalog:'/book/contents',//获取图书目录
    rankSave:'/book/rank/save',//图书评分
    bookShelf:'/book/shelf/get',//获取图书存储书架状态
    bookSave:'/book/shelf/save',//加入书架
    bookRemove:'/book/shelf/remove',//移除书架
    searchList:'/book/search-list',//获取图书列表
    categoryList:'/book/category/list/v2',//获取分类列表
    joinDay:'/user/day',//获取用户加入天数
}